version: "3.8"

services:

  # -------------------------
  # PostgreSQL Database
  # -------------------------
  postgres:
    image: postgres:15
    container_name: study-db
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: studydb

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    # IMPORTANT: ensures DB is ready before other services connect
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d studydb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


  # -------------------------
  # AUTH SERVICE (Flask API)
  # -------------------------
  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always

    ports:
      - "5001:5001"

    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/studydb
      JWT_SECRET_KEY: super-secret-key

    depends_on:
      postgres:
        condition: service_healthy


  # -------------------------
  # STUDY SERVICE (Flask API)
  # -------------------------
  study-service:
    build: ./studysession-tracker-service
    container_name: study-service
    restart: always

    ports:
      - "5002:5002"

    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/studydb
      JWT_SECRET_KEY: super-secret-key

    depends_on:
      postgres:
        condition: service_healthy


  # -------------------------
  # FRONTEND (React + Nginx)
  # -------------------------
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always

    ports:
      - "3000:80"

    depends_on:
      - auth-service
      - study-service


# -------------------------
# Persistent storage
# -------------------------
volumes:
  pgdata: