# docker compose used to run multiple docker containers
# Version of Docker Compose syntax
version: "3.8"

# Define services (containers)
services:

  # -------------------------
  # PostgreSQL Database
  # -------------------------
  postgres:
    image: postgres:15
    container_name: study-db
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: studydb

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data


  # -------------------------
  # AUTH SERVICE (Flask API)
  # -------------------------
  auth-service:
    build: ./auth-service   # build use specific folder to run dockerfile place there
    container_name: auth-service

    restart: always

    ports:
      - "5001:5001"

    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/studydb

    # depends mean this happens after always postgress container run
    depends_on:
      - postgres


  # -------------------------
  # STUDY SERVICE (Flask API)
  # -------------------------
  study-service:
    build: ./studysession-tracker-service
    container_name: study-service

    restart: always

    ports:
      - "5002:5002"

    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/studydb

    depends_on:
      - postgres


  # -------------------------
  # FRONTEND (React + Nginx)
  # -------------------------
  frontend:
    build: ./frontend
    container_name: frontend

    restart: always

    ports:
      - "3000:80"

    depends_on:
      - auth-service
      - study-service


# -------------------------
# Persistent volume for DB
# -------------------------
volumes:
  pgdata: