name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:

  backend-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # =========================
      # AUTH SERVICE
      # =========================
      - name: Install Auth Service Dependencies
        working-directory: ./auth-service
        run: pip install -r requirements.txt

      - name: Test Auth Service
        working-directory: ./auth-service
        run: PYTHONPATH=. pytest -v

      - name: Lint Auth Service
        working-directory: ./auth-service
        run: |
          pip install flake8
          flake8 .

      # =========================
      # STUDY SERVICE
      # =========================
      - name: Install Study Service Dependencies
        working-directory: ./studysession-tracker-service
        run: pip install -r requirements.txt

      - name: Test Study Service
        working-directory: ./studysession-tracker-service
        run: PYTHONPATH=. pytest -v

      - name: Lint Study Service
        working-directory: ./studysession-tracker-service
        run: |
          pip install flake8
          flake8 .


  frontend:
    runs-on: ubuntu-latest
    needs: backend-services

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Lint Code
        working-directory: ./frontend
        run: npm run lint || echo "No lint configured"

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build


  docker:
    runs-on: ubuntu-latest
    needs: [backend-services, frontend]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # =========================
      # BUILD IMAGES
      # =========================
      - name: Build Auth Service Image
        run: docker build -t myapp-auth ./auth-service

      - name: Build Study Service Image
        run: docker build -t myapp-study ./studysession-tracker-service

      - name: Build Frontend Image
        run: docker build -t myapp-frontend ./frontend

      # =========================
      # PUSH IMAGES
      # =========================
      - name: Push Images
        run: |
          docker push myapp-auth
          docker push myapp-study
          docker push myapp-frontend